name: VenturaCalendar
main: me.M0dii.VenturaCalendar.VenturaCalendar
description: VenturaCalendar by M0dii
version: 1.0
api-version: 1.16
author: M0dii
commands:
  venturacalendar:
    description: Base command
    permission: venturacalendar.command.vc
    usage: /<command>
    aliases: [venturacal, vc]
  calendar:
    description: Calendar command
    permission: venturacalendar.command.calendar
    usage: /<command>
permissions:
  venturacalendar.command.vc:
    description: Permission to use base command
    default: op
  venturacalendar.command.calendar:
    description: Command to open calendar
  TheTime.calendar:
    description: Gives access to all TheTime calendar commands.
    children:
      TheTime.calendar.default: true
      TheTime.calendar.TimeSystem: true