name: VenturaCalendar
main: me.m0dii.venturacalendar.VenturaCalendar
description: VenturaCalendar by M0dii
version: 1.3.0
api-version: 1.13
author: M0dii
softdepend: [PlaceholderAPI]
commands:
  venturacalendar:
    description: Base command
    permission: venturacalendar.command.vc
    usage: /<command>
    aliases: [venturacal, vc]
  calendar:
    description: Calendar command
    permission: venturacalendar.command.calendar
    usage: /<command>
permissions:
  venturacalendar.command.venturacalendar:
    description: Permission to use base command
    default: op
  venturacalendar.command.changetime:
    description: Permission to add/subtract time, set starting year
  venturacalendar.command.reload:
    description: Permission to reload the plugin
    default: op
  venturacalendar.command.calendar:
    description: Permission to use the calendar
  venturacalendar.command.timesystem:
    description: Permission to use different timesystems