## VenturaCalendar
## by M0dii
#
# Here you can set up different time-systems.
#
# The time-system time will be used by specified world name.
# If set to "current" it will use the current world the player is in.
#
# If you want to use real-life calendar:
#
# make sure the months and their days are equal to real life ones
# set the starting year to 1970
#
# ticksPerSecond: 20
# secondsPerMinute: 60
# minutesPerHour: 60
time-systems:
  default:
    world-name: 'world'
    real-time:
      enabled: false
      # If set to false, real-time will use local machine time
      use-time-zone: false
      time-zone: 'Europe/Germany'
    ticks-per-second: 20
    seconds-per-minute: 5
    minutes-per-hour: 10
    hours-per-day: 24
    days-per-week: 7
    months-per-year: 12
    # You can set the time offsets here.
    # Example:
    # If the world is new (time = 0), you can off-set the month by 1
    # and the calendar will start from the second month as if one month has passed.
    month-offset: 0
    week-offset: 0
    day-offset: 0
    # If the world is not set to real-time, it will use this starting year.
    # When the world is new, or you use /minecraft:time set 0,
    # it will use this value as starting year.
    starting-year: 0
    days:
      - 'Monday'
      - 'Tuesday'
      - 'Wednesday'
      - 'Thursday'
      - 'Friday'
      - 'Saturday'
      - 'Sunday'
    months:
    # The values are split by ', '
    # - 'Month Name, Days, Season Name'
      - 'January, 31, Winter'
      - 'February, 28, Winter'
      - 'March, 31, Winter'
      - 'April, 30, Spring'
      - 'May, 31, Spring'
      - 'June, 30, Spring'
      - 'July, 31, Summer'
      - 'August, 31, Summer'
      - 'September, 30, Summer'
      - 'October, 31, Autumn'
      - 'November, 30, Autumn'
      - 'December, 31, Autumn'
      - 'January, 30, Winter'
    eras:
      '1':
        name: 'Bronze Age'
        startYear: -3000
        endYear: -1050
      '2':
        name: 'Iron Age'
        startYear: -1049
        endYear: -500